-- ============================================================
-- Phase 1: Foundation — Grants
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- SUPPLY_CHAIN_ADMIN: full ownership of the database and schema
GRANT OWNERSHIP ON DATABASE SUPPLY_CHAIN_DB TO ROLE SUPPLY_CHAIN_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE SUPPLY_CHAIN_ADMIN COPY CURRENT GRANTS;

-- Warehouse access for all roles
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SUPPLY_CHAIN_ADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SC_AGENT_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE PROCUREMENT_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE PLANNING_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE LOGISTICS_ROLE;

-- Database-level usage for child roles
GRANT USAGE ON DATABASE SUPPLY_CHAIN_DB TO ROLE SC_AGENT_ROLE;
GRANT USAGE ON DATABASE SUPPLY_CHAIN_DB TO ROLE PROCUREMENT_ROLE;
GRANT USAGE ON DATABASE SUPPLY_CHAIN_DB TO ROLE PLANNING_ROLE;
GRANT USAGE ON DATABASE SUPPLY_CHAIN_DB TO ROLE LOGISTICS_ROLE;

-- Schema-level usage for child roles
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE SC_AGENT_ROLE;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE PROCUREMENT_ROLE;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE PLANNING_ROLE;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE LOGISTICS_ROLE;

-- SC_AGENT_ROLE: full read on all current and future tables/views in SCM
GRANT SELECT ON ALL TABLES IN SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE SC_AGENT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE SC_AGENT_ROLE;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE SC_AGENT_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE SC_AGENT_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE SC_AGENT_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE SC_AGENT_ROLE;

-- PROCUREMENT_ROLE: read on all tables + write on ORDERS, ORDER_LINES, SUPPLIERS, SUPPLY_CHAIN_ALERTS
GRANT SELECT ON ALL TABLES IN SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE PROCUREMENT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE PROCUREMENT_ROLE;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE PROCUREMENT_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE PROCUREMENT_ROLE;

-- PLANNING_ROLE: read on all tables
GRANT SELECT ON ALL TABLES IN SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE PLANNING_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE PLANNING_ROLE;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE PLANNING_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE PLANNING_ROLE;

-- LOGISTICS_ROLE: read on all tables + write on SHIPMENTS, SUPPLY_CHAIN_ALERTS
GRANT SELECT ON ALL TABLES IN SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE LOGISTICS_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE LOGISTICS_ROLE;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE LOGISTICS_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE LOGISTICS_ROLE;

-- Semantic view access for all roles
GRANT CREATE SEMANTIC VIEW ON SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE SUPPLY_CHAIN_ADMIN;
GRANT SELECT ON FUTURE SEMANTIC VIEWS IN SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE SC_AGENT_ROLE;
GRANT SELECT ON FUTURE SEMANTIC VIEWS IN SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE PROCUREMENT_ROLE;
GRANT SELECT ON FUTURE SEMANTIC VIEWS IN SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE PLANNING_ROLE;
GRANT SELECT ON FUTURE SEMANTIC VIEWS IN SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE LOGISTICS_ROLE;

-- Agent creation and usage privileges
GRANT CREATE AGENT ON SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE SUPPLY_CHAIN_ADMIN;

-- Cortex user role for agent access
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE SC_AGENT_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE PROCUREMENT_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE PLANNING_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE LOGISTICS_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE SUPPLY_CHAIN_ADMIN;

-- Stage, procedure, function creation for admin
GRANT CREATE STAGE ON SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE SUPPLY_CHAIN_ADMIN;
GRANT CREATE PROCEDURE ON SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE SUPPLY_CHAIN_ADMIN;
GRANT CREATE FUNCTION ON SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE SUPPLY_CHAIN_ADMIN;
GRANT CREATE TABLE ON SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE SUPPLY_CHAIN_ADMIN;
GRANT CREATE DYNAMIC TABLE ON SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE SUPPLY_CHAIN_ADMIN;
GRANT CREATE STREAM ON SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE SUPPLY_CHAIN_ADMIN;
GRANT CREATE TASK ON SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE SUPPLY_CHAIN_ADMIN;
GRANT CREATE STREAMLIT ON SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE SUPPLY_CHAIN_ADMIN;
GRANT CREATE MASKING POLICY ON SCHEMA SUPPLY_CHAIN_DB.SCM TO ROLE SUPPLY_CHAIN_ADMIN;

-- Allow admin to execute tasks
GRANT EXECUTE TASK ON ACCOUNT TO ROLE SUPPLY_CHAIN_ADMIN;

-- Assign current user to SUPPLY_CHAIN_ADMIN
GRANT ROLE SUPPLY_CHAIN_ADMIN TO USER PRABHJOT;
