-- ============================================================
-- Automation 1: LOGISTICS_DAILY_BRIEF
-- Team: Logistics
-- Cadence: Weekdays at 7:30 AM IST (Asia/Kolkata)
-- MCP: SUPPLY_CHAIN_DB.SCM.GMAIL (email), SUPPLY_CHAIN_DB.SCM.SLACK_MCP (Slack alerts)
-- Read-only: Yes (default RSS)
-- ============================================================
--
-- Deploy via CoCo CLI:
--
-- cortex automation create \
--   --name LOGISTICS_DAILY_BRIEF \
--   --schedule "weekdays at 7:30am" \
--   --timezone "Asia/Kolkata" \
--   --mcp SUPPLY_CHAIN_DB.SCM.GMAIL \
--   --mcp SUPPLY_CHAIN_DB.SCM.SLACK_MCP \
--   --no-workspace \
--   --prompt-file "12_automations/logistics_daily_brief_prompt.md"
--
-- Test first (one-shot dry run):
--   cortex automation create \
--     --name LOGISTICS_DAILY_BRIEF_TEST \
--     --schedule "in 2 minutes" \
--     --timezone "Asia/Kolkata" \
--     --mcp SUPPLY_CHAIN_DB.SCM.GMAIL \
--     --mcp SUPPLY_CHAIN_DB.SCM.SLACK_MCP \
--     --no-workspace \
--     --prompt-file "12_automations/logistics_daily_brief_prompt.md"
--
-- Management:
--   cortex automation list
--   cortex automation doctor LOGISTICS_DAILY_BRIEF
--   cortex automation suspend LOGISTICS_DAILY_BRIEF
--   cortex automation resume LOGISTICS_DAILY_BRIEF
--   cortex automation drop LOGISTICS_DAILY_BRIEF
