-- ============================================================
-- Phase 3: Masking Policies (5 policies)
-- Column-level security enforced by Snowflake engine.
-- SC_AGENT_ROLE + SUPPLY_CHAIN_ADMIN bypass all masks.
-- ============================================================

USE ROLE SUPPLY_CHAIN_ADMIN;
USE DATABASE SUPPLY_CHAIN_DB;
USE SCHEMA SCM;

-- ===================== POLICY 1: COST_DATA_MASK =====================
-- Masks: freight_cost, unit_cost (shipment lines), unit_price (order lines), DT_LANDED_COST columns
-- Visible to: PROCUREMENT_ROLE, SC_AGENT_ROLE, SUPPLY_CHAIN_ADMIN
CREATE OR REPLACE MASKING POLICY COST_DATA_MASK AS (val NUMBER(10,2))
  RETURNS NUMBER(10,2) ->
  CASE
    WHEN CURRENT_ROLE() IN ('PROCUREMENT_ROLE', 'SC_AGENT_ROLE', 'SUPPLY_CHAIN_ADMIN', 'ACCOUNTADMIN')
    THEN val
    ELSE NULL
  END;

-- ===================== POLICY 2: SUPPLIER_DETAIL_MASK =====================
-- Masks: quality_rating (SUPPLIERS), carrier (SHIPMENTS, DT_DELIVERY_PERF)
-- Visible to: PROCUREMENT_ROLE, LOGISTICS_ROLE, SC_AGENT_ROLE, SUPPLY_CHAIN_ADMIN
CREATE OR REPLACE MASKING POLICY SUPPLIER_DETAIL_MASK AS (val VARCHAR)
  RETURNS VARCHAR ->
  CASE
    WHEN CURRENT_ROLE() IN ('PROCUREMENT_ROLE', 'LOGISTICS_ROLE', 'SC_AGENT_ROLE', 'SUPPLY_CHAIN_ADMIN', 'ACCOUNTADMIN')
    THEN val
    ELSE NULL
  END;

-- ===================== POLICY 3: CUSTOMER_DATA_MASK =====================
-- Masks: customer_id, customer name columns
-- Visible to: PLANNING_ROLE, SC_AGENT_ROLE, SUPPLY_CHAIN_ADMIN
CREATE OR REPLACE MASKING POLICY CUSTOMER_DATA_MASK AS (val VARCHAR)
  RETURNS VARCHAR ->
  CASE
    WHEN CURRENT_ROLE() IN ('PLANNING_ROLE', 'SC_AGENT_ROLE', 'SUPPLY_CHAIN_ADMIN', 'ACCOUNTADMIN')
    THEN val
    ELSE NULL
  END;

-- ===================== POLICY 4: SAFETY_STOCK_MASK =====================
-- Masks: safety_stock_qty
-- Visible to: PLANNING_ROLE, SC_AGENT_ROLE, SUPPLY_CHAIN_ADMIN
CREATE OR REPLACE MASKING POLICY SAFETY_STOCK_MASK AS (val INT)
  RETURNS INT ->
  CASE
    WHEN CURRENT_ROLE() IN ('PLANNING_ROLE', 'SC_AGENT_ROLE', 'SUPPLY_CHAIN_ADMIN', 'ACCOUNTADMIN')
    THEN val
    ELSE NULL
  END;

-- ===================== POLICY 5: REORDER_POINT_MASK =====================
-- Masks: reorder_point
-- Visible to: PROCUREMENT_ROLE, PLANNING_ROLE, SC_AGENT_ROLE, SUPPLY_CHAIN_ADMIN
CREATE OR REPLACE MASKING POLICY REORDER_POINT_MASK AS (val INT)
  RETURNS INT ->
  CASE
    WHEN CURRENT_ROLE() IN ('PROCUREMENT_ROLE', 'PLANNING_ROLE', 'SC_AGENT_ROLE', 'SUPPLY_CHAIN_ADMIN', 'ACCOUNTADMIN')
    THEN val
    ELSE NULL
  END;

-- ===================== APPLY POLICIES TO BASE TABLES =====================

-- COST_DATA_MASK
ALTER TABLE SHIPMENTS MODIFY COLUMN freight_cost SET MASKING POLICY COST_DATA_MASK;
ALTER TABLE SHIPMENT_LINES MODIFY COLUMN unit_cost SET MASKING POLICY COST_DATA_MASK;
ALTER TABLE ORDER_LINES MODIFY COLUMN unit_price SET MASKING POLICY COST_DATA_MASK;

-- SUPPLIER_DETAIL_MASK
ALTER TABLE SUPPLIERS MODIFY COLUMN quality_rating SET MASKING POLICY SUPPLIER_DETAIL_MASK;
ALTER TABLE SHIPMENTS MODIFY COLUMN carrier SET MASKING POLICY SUPPLIER_DETAIL_MASK;

-- CUSTOMER_DATA_MASK (on CUSTOMERS table — all sensitive columns)
ALTER TABLE CUSTOMERS MODIFY COLUMN name SET MASKING POLICY CUSTOMER_DATA_MASK;
ALTER TABLE CUSTOMERS MODIFY COLUMN segment SET MASKING POLICY CUSTOMER_DATA_MASK;
ALTER TABLE CUSTOMERS MODIFY COLUMN region SET MASKING POLICY CUSTOMER_DATA_MASK;

-- SAFETY_STOCK_MASK
ALTER TABLE INVENTORY MODIFY COLUMN safety_stock_qty SET MASKING POLICY SAFETY_STOCK_MASK;

-- REORDER_POINT_MASK
ALTER TABLE INVENTORY MODIFY COLUMN reorder_point SET MASKING POLICY REORDER_POINT_MASK;
